Team member page
humanoidsbv/team-awesome-fabiano pull request #27
Opened 2022-03-03 08:35 UTC by fabianovangool

2022-03-03 09:01 UTC, RubenWerdmuller submitted a review, later dismissed

2022-03-08 10:07 UTC, saravdberg commented on pages/index.tsx
> +      clients,
Sort props alphabetically

2022-03-08 10:09 UTC, saravdberg commented on src/components/context-provider/ContextProvider.tsx
> +    teamMembers: useState<TeamMemberTypes.MemberEntryProps[]>([]),
Sort Alphabetically 😉

2022-03-08 10:17 UTC, saravdberg commented on src/components/member-entries/MemberEntries.tsx
> +        buttonIcon={true}
Sort props alphabetically 👯

2022-03-08 10:18 UTC, saravdberg commented on src/components/member-entries/MemberEntries.tsx
> +          handleAddButtonClick={handleClick}
ABC 👯

2022-03-08 10:19 UTC, saravdberg commented on src/components/member-entries/MemberEntries.types.ts
> +  id?: number;
abcccdefg

2022-03-08 10:19 UTC, saravdberg commented on src/components/member-entry/MemberEntry.styled.ts
> +  align-items: center;
abc

2022-03-08 10:20 UTC, saravdberg commented on src/components/member-entry/MemberEntry.styled.ts
> +  align-items: center;
Gonna stop writing abc, but also counts for all the stuff below this!

2022-03-08 10:22 UTC, saravdberg commented on pages/index.tsx
> +            <TimeEntries {...{ clients, timeEntries }} />
It is usually only recommended to deconstruct props this way when you pass them to your Styled Components. So if it was `<Styled.Container {...{ isActive }} />` for example.

2022-03-08 10:24 UTC, saravdberg commented on src/components/member-modal/MemberModal.styled.ts
> +    z-index: 80;
On my laptop screen, the modal is too big for the window. Don't think it is worth changing now, but keep in mind to check the styling on multiple screen sizes.

2022-03-08 10:26 UTC, saravdberg commented on src/components/member-modal/MemberModal.styled.ts
> +  padding: 0 20px 0 20px;
`padding: 0 20px`

2022-03-08 10:26 UTC, saravdberg commented on src/components/member-modal/MemberModal.styled.ts
> +export const Title = styled.div`
If the name is Title, you would expect an h1 element instead of a div.

2022-03-08 10:27 UTC, saravdberg commented on src/components/member-modal/MemberModal.styled.ts
> +export const Buttons = styled.div`
This name would also suggest a button, not a div.

2022-03-08 10:28 UTC, saravdberg commented on src/components/member-modal/MemberModal.tsx
> +  handleAddButtonClick,
Sort props

2022-03-08 10:32 UTC, saravdberg requested changes
Lekker bezug!! 🥳

2022-03-08 10:34 UTC, saravdberg commented on src/components/member-entries/MemberEntries.tsx
> +  type MemberKeysValues =
Since your variabele is called `memberSort` I would call your type something accordingly. MemberSortValues or something.

2022-03-08 10:40 UTC, saravdberg approved these changes

2022-03-08 10:46 UTC, HermanVulkers approved these changes

2022-03-08 10:47 UTC, merged