add testing and add errorless eslint
humanoidsbv/team-awesome-fabiano pull request #34
Opened 2022-03-09 10:07 UTC by fabianovangool

2022-03-10 15:26 UTC, RubenWerdmuller commented on src/components/member-modal/MemberModal.test.tsx
> +  it("Press cancel, onClose gets called", () => {
the `it press cancel` grammer is a bit odd to read ;)

2022-03-10 15:26 UTC, brambrink reviewed
Looking very nice! 🆒

2022-03-10 15:26 UTC, RubenWerdmuller commented on src/components/member-modal/MemberModal.tsx
> +        // eslint-disable-next-line react/jsx-indent
Usually, you would fix this here or through ESLint

2022-03-11 13:40 UTC, brambrink approved these changes
Looks good!

2022-03-14 10:50 UTC, amijsb requested changes
Good busy 🚀

2022-03-14 10:50 UTC, amijsb commented on src/components/member-entries/MemberEntries.test.tsx
> +  lastName: "Ferrari",
Nice 🏎

2022-03-14 10:50 UTC, amijsb commented on .github/workflows/build-app.prod.yml
> +        run: npm run lint
I'd run `npm run lint` before running `npm run build`.

2022-03-14 10:50 UTC, amijsb commented on src/components/time-entry/TimeEntry.tsx
> +        // eslint-disable-next-line react/jsx-no-bind
Do you need this eslint exception?

2022-03-14 10:50 UTC, amijsb commented on src/components/time-entries/TimeEntries.tsx
> +          // eslint-disable-next-line react/jsx-no-bind
Do you need this eslint exception?

2022-03-14 10:50 UTC, amijsb commented on src/components/time-entries/TimeEntries.tsx
> +          // eslint-disable-next-line react/jsx-no-bind
```suggestion
         handleAddButtonClick={() => handleClick()}
```

2022-03-14 10:50 UTC, amijsb commented on src/components/time-entry/TimeEntry.tsx
> +        // eslint-disable-next-line react/jsx-no-bind
```suggestion
        onClick={() => handleDelete()}
```

2022-03-14 13:24 UTC, amijsb approved these changes
🏎🏎🏎💨💨💨

2022-03-14 13:26 UTC, merged